version: '3.7'

services:
  sustainability:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustainability
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
      - "traefik.http.routers.sustainability.tls=true"
      - "traefik.http.routers.sustainability.rule=Host(`sustainability.safaripro.net`)"
      - "traefik.http.routers.sustainability.entrypoints=websecure"
      - "traefik.http.routers.sustainability.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sustainability.service=sustainability"
      - "traefik.http.services.sustainability.loadbalancer.server.port=8001"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - static_volume:/app/sustainability/staticfiles
      - media_volume:/app/sustainability/media
    ports:
      - "8002:80"
    depends_on:
      - sustainability
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  media_volume:
  static_volume:
  app:
