# version: '3.8'

services:
  traefiks:
    image: traefik:2.8
    container_name: traefiks
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.routers.traefik.service=api@internal"

  sustainability:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustainability
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
      - "traefik.http.routers.sustainability.tls=true"
      - "traefik.http.routers.sustainability.rule=Host(`http://sustainability.safaripro.net`)"
      - "traefik.http.routers.sustainability.entrypoints=websecure"
      - "traefik.http.routers.sustainability.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sustainability.service=sustainability"
      - "traefik.http.services.sustainability.loadbalancer.server.port=8010"

  

  

  nginx:
    image: nginx
    volumes:
      - static_volume:/app/sustainability/staticfiles
      - media_volume:/app/sustainability/media
    ports:
      - 8001:80
    depends_on:
      - sustainability

networks:
  proxy:
    external: true

volumes:
  media_volume:
  static_volume:
  app:
