services:
  sustainability:
    image: safaripro-sustainability
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustainability
    restart: always
    # only for developement
    volumes:
      - .:/app
    environment:
      - DB_HOST=database_sust
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NATS_URL=nats://nats_sustain:4223
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - "8003:8003"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.sustainability.rule=Host(`sustainability.safaripro.net`)"
      - "traefik.http.routers.sustainability.entrypoints=websecure"
      - "traefik.http.routers.sustainability.tls=true"
      - "traefik.http.routers.sustainability.tls.certresolver=letsencrypt"
      - "traefik.http.services.sustainability.loadbalancer.server.port=8003"

  redis:
    image: redis:6
    container_name: redis
    networks:
      - proxy
    ports:
      - "6379:6379"

  nats:
    image: nats:latest
    container_name: nats_sustain
    networks:
      - proxy
    ports:
      - "4223:4222"
      - "6223:6222"
      - "8223:8222"
    restart: unless-stopped

  database_sust:
    image: postgres:13
    container_name: database_sust
    networks:
      - proxy
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: unless-stopped

    volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  proxy:
    external: true
