name: Deploy Django App to DigitalOcean

on:
  push:
    branches:
      - main  # Adjust this if your branch name is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image Locally
      run: |
        docker build -t django-app:latest .

    - name: Save Docker Image as a Tar File
      run: |
        docker save -o django-app.tar django-app:latest

    - name: Upload Docker Image to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_IP_SUSTAINABILITY }}
        username: root
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        source: "django-app.tar"
        target: "/root"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into DigitalOcean and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_IP }}
        username: root
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          docker load -i /root/django-app.tar
          docker stop django-app || true
          docker rm django-app || true
          docker run -d --name django-app -p 8003:8003 django-app:latest
